### ISSUE TITLE
Update AGP

### ISSUE THREAD

**Issue by penn5** [korlibs/easy-kotlin-mpp-gradle-plugin#15]
`This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.2 or newer.`

**Comment by soywiz** [comment]
Can you provide more details? Under which circumstances does that happen? Is that related to easy-kotlin-mpp-gradle-plugin? Which version of which library is outdated?

**Comment by penn5** [comment]
It is using 4.2.0-rc02 but should use 4.2.0
